public enum ETipoPruebaPresentacion : byte
{
    Dinamica = 0,  
    HabitosEstudio = 1,
    Dominos = 2,
    TermanMerrill = 6,
    Kuder = 7,
    Allport = 8,
    FrasesIncompletasSacks = 9,
    Cleaver = 10,
    Chaside = 11,
    Rotter = 12,
    FrasesIncompletasVocacionales = 13,
    Zavic = 14,
    Raven = 15,
    Kostick = 16,
    Bullying = 17,
    Socioeconomico = 18,
    Autoconcepto = 19,
    Actitudes = 20,
    Empatia = 21,
    Humor = 22,
    Victimizacion = 23,
    Ciberbullying = 24,
    Violencia = 25,
    Comunicacion = 26,
    ImagenCorporal = 27,
    Ansiedad = 28,
    Depresion = 29,
    EstilosdeAprendizaje = 30,
    InteligengiasMultiples = 31,
    InventarioDeIntereses = 32,
    InventarioHerreraMontes = 33,
    SucesosDeVida =34,
    Luscher = 35
}

